name: ethiopian_date_picker
description: A customizable Ethiopian date picker for Flutter with localization.
version: 0.0.1 # Start with 0.0.1. You'll increment this for future releases.
homepage: https://github.com/B14ever/ethiopian_date_picker # IMPORTANT: Replace with your actual GitHub repository URL
repository: https://github.com/B14ever/ethiopian_date_picker # IMPORTANT: Replace with your actual GitHub repository URL
issue_tracker: https://github.com/B14ever/ethiopian_date_picker/issues # IMPORTANT: Replace with your actual GitHub repository URL

environment:
  sdk: '>=3.0.0 <4.0.0' # Recommended broader range for Dart 3.x
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Add any other dependencies your package actually uses.
  # Based on your previous code, you might not have any direct external deps
  # beyond Flutter itself, unless you added something for localization.
  # Example if you added intl for future date formatting:
  # intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Sticking to a commonly used version for stability

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # Your package might not have any assets or fonts, so these sections can remain commented out
  # unless you add them later.

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package